# SwiftLint Configuration for OddsTask
# This configuration uses warnings for all rules (no errors)

# Paths to include/exclude
included:
  - OddsTask
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - .swiftpm

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments for development
  - trailing_whitespace # Can be auto-fixed
  - large_tuple # Allow tuples with more than 2 members

# Rule configurations - All set to warnings only
line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400

function_body_length:
  warning: 50

function_parameter_count:
  warning: 5

type_body_length:
  warning: 200

cyclomatic_complexity:
  warning: 10

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
  excluded:
    - id
    - url
    - uri

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 40

# Custom rules for the project - All warnings
custom_rules:
  # Ensure proper MARK usage
  mark_usage:
    name: "MARK Usage"
    regex: '\/\/\s*MARK:\s*-\s*[A-Z]'
    message: "MARK comments should follow the pattern: // MARK: - Section Name"
    severity: warning

  # Discourage force unwrapping in production code
  force_unwrap_production:
    name: "Force Unwrap in Production"
    regex: '!\s*(?!\/\/)'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping in production code. Use safe unwrapping instead."
    severity: warning

  # Ensure proper error handling
  empty_catch:
    name: "Empty Catch Block"
    regex: 'catch\s*\{\s*\}'
    message: "Empty catch blocks should be avoided. Handle errors appropriately."
    severity: warning

# Reporter type
reporter: "xcode"

# Strict mode (treat warnings as errors in CI)
strict: false

# Only warnings, no errors
only_rules: []
